### ISSUE TITLE
Generate Fortran 2003 Interfaces at build-time/configure-time.

### ISSUE THREAD

**Issue by MehdiChinoune** [LLNL/sundials#100]
Currently we couldn't package sundials for MSYS2/MinGW-w64 because we build all sundials dependencies with 32bit indexing.
It would be better if you add an option to generate Fortran 2003 interfaces at configure-time/build-time, to make sundials more configurable and easier to package for all platforms.

**Comment by balos1** [comment]
I agree that it would be nice for the Fortran 2003 interfaces to be configurable. It is something we want to do, but have not had the time to do yet.
