### ISSUE TITLE
OpenMP Example Doesn't Work

### ISSUE THREAD

**Issue by dxwu88** [LLNL/sundials#103]
I tested the installed example project openmpdev at ./examples/nvector/openmpdev on Ubuntu. But it didn't work. I changed many functions end with MPDEV to MP. But there are still several functions without definitions, such as N_VGetDeviceArrayPointer_OpenMP and N_VGetHostArrayPointer_OpenMP.

**Comment by gardner48** [comment]
@dxwu88 the example `examples/nvector/openmpdev` is for the OpenMPDEV vector which uses device offloading to target GPUs and includes some additional functions to deal with host and device memory spaces. For an example using the OpenMP vector to target CPUs, see the example in `examples/nvector/C_openmp`.

**Comment by dxwu88** [comment]
David, thank you very much for pointing me to the right OpenMP example.
