### ISSUE TITLE
Need guidance on SUNContext creation/destruction

### ISSUE THREAD

**Issue by bangerth** [LLNL/sundials#109]
https://github.com/LLNL/sundials/blob/74b6be71f3d733cc93a2bcbefd6c37b7b0db3341/doc/shared/sundials/SUNContext.rst describes the new SUNContext class introduced in SUNDIALS 6.0. It specifically says that one needs a different context object for each thread of execution, but this is often difficult to guarantee. For example, one may do a parallel `for_each()` call that loops over a set of quadrature points, at each of which an ODE has to be solved. Thread creation happens in the task scheduler that underlies the parallel `for_each()` call. The only way to guarantee a thread-unique context object is to create it just before the creation of the SUNDIALS solver, and destroy it right afterwards.

The question therefore is: Is the creation/destruction of context objects cheap? If so, could the page referenced above be updated for this use case?

There is a separate issue in that a SUNDIALS solver may be created in one thread but then used in another. What is the guidance in this case?

**Comment by balos1** [comment]
> The question therefore is: Is the creation/destruction of context objects cheap? If so, could the page referenced above be updated for this use case?

Yes, the creation/destruction of the context object is cheap (much much cheaper than the creation/initialization of the SUNDIALS solver). So you could do what you have described without worrying too much. However, in a related question that came through to the sundials-users@llnl.gov mailing list, I provided something like the following example:

```c
 SUNContext sunctxs[num_threads];
 int cvode_initialized[num_threads];
 void* cvode_mem[num_threads];

 // Create
 for (int i = 0; i < num_threads; i++) {
    sunctxs[i] = SUNContext_Create(...);
    cvode_mem[i] = CVodeCreate(..., sunctxs[i]);
    cvode_initialized[i] = 0; // not yet initialized
 }

 // Solve
 #pragma omp parallel for
 for (int i = 0; i < num_problems; i++) {
    int retval = 0;
    int tid = omp_get_thread_num();
    if (!cvode_initialized[tid]) 
      retval = CVodeInit(cvode_mem[tid], ...);
    else
      retval = CVodeReInit(cvode_mem[tid], ...);
    CVode(cvode_mem[i], ...);
 }

 // Free
 for (int i = 0; i < num_threads; i++) {
    CVodeFree(&cvode_mem[i]);
    SUNContext_Free(&sunctxs[i]);
 }
```

The difference from this example and what you described (I think) would be that the contexts in this example could be reused in the parallel loop if there are more problems than threads. The reuse of the CVODE instances would provide way more savings than the reuse of the contexts though. I will add this example to the documentation section you refer to, and I will add a note about the creation/destruction of the context being cheap.

**Comment by balos1** [comment]
I would also like to add a fully functioning example that does this to our example suite, but that might take a bit more time.

**Comment by bangerth** [comment]
Much appreciated. One could, at least in programming languages that easily support this, use a thread-local variable for this. The issue in your example is that it assumes we know up front how many threads there are, and that `omp_get_thread_num()` indexes them sequentially from zero to `num_threads`. The former is probably only true if you set up OpenMP in a very specific way and never create threads outside OpenMP. The latter may or may not be true.

Any thoughts about the second issue in my original question (where the SUNDIALS solver is used from different threads)?

**Comment by balos1** [comment]
That is correct about my specific OpenMP example -- a more complicated case could easily break some of the assumptions in it. 

> Any thoughts about the second issue in my original question (where the SUNDIALS solver is used from different threads)?

Yes, the SUNDIALS context can be used in a different thread than which it was created. The only requirement is that the context object is not accessed from multiple threads concurrently. I.e. one context should not used with multiple SUNDIALS solver objects that are concurrently running on different threads, but it could be used for multiple SUNDIALS objects that are guaranteed to execute sequentially with respect to one another.

**Comment by bangerth** [comment]
Thanks again.

I believe that you can guarantee these sorts of constraints on your context objects in task-based programming, but just barely so. If you create a SUNDIALS solver for each quadrature point, to give just one example, and then schedule a whole bunch of tasks to advance each quadrature point by one macro-timestep, then keep doing this workflow for macro-timestep after macro-timestep, you can't guarantee which thread each task lands on, and consequently which context object is used on which thread.

Of course, tautologically, each context object is used on only one thread at a time as long as the SUNDIALS itself is not starting tasks, simply because in that scenario, each SUNDIALS solver call is run to completion on the same thread where it was started. But that's about it. In general, if a task has a synchronization point, another task may run on the same thread while the first task is stopped at the synchronization point. You have very little guarantees in task-based programming.

**Comment by bangerth** [comment]
Thanks again.

I believe that you can guarantee these sorts of constraints on your context objects in task-based programming, but just barely so. If you create a SUNDIALS solver for each quadrature point, to give just one example, and then schedule a whole bunch of tasks to advance each quadrature point by one macro-timestep, then keep doing this workflow for macro-timestep after macro-timestep, you can't guarantee which thread each task lands on, and consequently which context object is used on which thread.

Of course, tautologically, each context object is used on only one thread at a time as long as the SUNDIALS itself is not starting tasks, simply because in that scenario, each SUNDIALS solver call is run to completion on the same thread where it was started. But that's about it. In general, if a task has a synchronization point, another task may run on the same thread while the first task is stopped at the synchronization point. You have very little guarantees in task-based programming.

**Comment by balos1** [comment]
> In general, if a task has a synchronization point, another task may run on the same thread while the first task is stopped at the synchronization point. You have very little guarantees in task-based programming.

That is a good point, so perhaps I should amend my statement. The requirement is that the SUNDIALS context is not associated with more than one SUNDIALS simulation (so a solver object and its associated vectors etc) simultaneously, regardless of if the simulations are actually executing concurrently. 

So in a task-based approach, it may be that the only practical solution is to create a SUNDIALS context right before creating the solver and destroying it right after destroying the solver. However, I do not want SUNDIALS to be too prescriptive here. So to address your concerns, I think revising the SUNDIALS documentation to be clear that

1. a  SUNDIALS context must only be associated with _one_ SUNDIALS simulation (a solver object and its associated vectors etc.) at a time,
2. the creation and destruction of a SUNContext is cheap,

would be appropriate. Then we may also include specific examples like the one I have provided as well as one showing creating/destroying a SUNContext in lockstep with the creation/destruction of the solver -- for inspiration, but not as the required or correct approaches for all use cases.

**Comment by bangerth** [comment]
Yes, that's how I think we'll implement things. Of course, in that case, it essentially becomes a private member of the solver object that could also have been created by the solver itself (with a getter function so one can set a profiler), but there is little effort involved in doing so in user space. 

The suggested changes to the documentation would certainly be useful!

**Comment by balos1** [comment]
>  Of course, in that case, it essentially becomes a private member of the solver object that could also have been created by the solver itself 

We actually considered this heavily. The primary issues with it are: it would mean all of the other objects (vector, linear solver etc) have to be created after the solver (which we don't require), and a user may have some auxiliary vector (perhaps for a temporary calculation), for example, that is part of a 'simulation',  but is not a member of the solver itself. For these reasons, we kept the creation of the SUNContext and solver separate. 

> The suggested changes to the documentation would certainly be useful!

Great, thanks again!

**Comment by balos1** [comment]
The docs have been updated with further details.

**Comment by bangerth** [comment]
This has been closed, but I can I ask a follow-up since I'm finally getting around to actually addressing this in deal.II:

In an implementation of the `clone_empty` callback for NVector objects, I now have this:
```
      N_Vector
      clone_empty(N_Vector w)
      {
        Assert(w != nullptr, ExcInternalError());
#if DEAL_II_SUNDIALS_VERSION_LT(6,0,0)                
        N_Vector v = N_VNewEmpty();
#else
        N_Vector v = N_VNewEmpty(w->sunctx);       // ****************
#endif    

        ...
```

The marked line is markedly not pretty because I'm accessing internal information of the `N_Vector` structure (or its anonymized version). What I need is a way to query the context of a vector in order to create a cloned copy of the vector, but I can not find a function in the `N_V*` interface that would provide this information. Am I looking in the wrong place?

**Comment by balos1** [comment]
You are not looking in the wrong place, there is not a function that gets the context from the `N_Vector`. The members of the generic `N_Vector` struct (`ops`, `content`) have always been considered public and directly accessible, so for consistency `sunctx` is treated the same.  In addition, I would consider getter/setters for these members to be 'trivial' and to be avoided (see https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-get).
