### ISSUE TITLE
cmake/SundialsSetupTPLs.cmake, HYPRE should be list ed after mph

### ISSUE THREAD

**Issue by ingutheil** [LLNL/sundials#110]
As HYPRE is a library using MPI, CMAKE_C_COMPILER is set to MPI_C_COMPILER which is not defined if ENABLE_HYPRE is checked before ENABLE_MPI. This leads to the error message
CMake Error at /dev/shm/mathprod/juwels/sundials/6.0.0/gomkl-2021b/easybuild_obj/HYPRE_TEST/CMakeLists.txt:14 (ADD_EXECUTABLE):
  C_STANDARD is set to invalid value ''
This is because in HYPRE_TEST/CMakeLists.txt
you have
SET(CMAKE_C_COMPILER )
SET(CMAKE_C_STANDARD "")
because MPI_C_COMPILER is empty

If I put the lines
# ---------------------------------------------------------------
# Find (and test) the hypre libraries
# ---------------------------------------------------------------

if(ENABLE_HYPRE)
  include(SundialsHypre)
  list(APPEND SUNDIALS_TPL_LIST "HYPRE")
endif()

after

# ---------------------------------------------------------------
# Find MPI.
# ---------------------------------------------------------------

if(ENABLE_MPI)
  include(SundialsMPI)
  list(APPEND SUNDIALS_TPL_LIST "MPI")
endif()

This problem is solved.

**Comment by balos1** [comment]
Fixed in SUNDIALS v6.1.0. Thanks!
