### ISSUE TITLE
Successful installation but error when running an example

### ISSUE THREAD

**Issue by surrutiaquir** [LLNL/sundials#116]
I followed the instructions to install `sundials` from [this tutorial](https://sundials.readthedocs.io/en/latest/Install_link.html?highlight=install) on my Apple Silicon Macbook and the installation seemed to work -no errors during the `make` process. But when I try to compile one of the examples manually (e.g. `instdit/examples/cvode/serial`), I get this very basic error message:

```
Sebastians-Macbook-Pro:serial surrutiaquir$ make
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -O3 -DNDEBUG -O3 -DNDEBUG -I/Users/surrutiaquir/Software/sundials/instdir/include -c cvAdvDiff_bnd.c
cvAdvDiff_bnd.c:37:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [cvAdvDiff_bnd.o] Error 1
```

I would be more than happy to provide the details of the configuration used during the installation, the details of my machine, or anything needed because I need to use this software for my research. Thank you so much in advance!

**Comment by balos1** [comment]
Hi @surrutiaquir,

We have not yet tried to build SUNDIALS on an Apple Silicon Macbook, so I am afraid I cannot be of much help. On Intel macs, an error like that typically was associated with missing the Xcode command line tools.
