### ISSUE TITLE
Question about the ARKODE

### ISSUE THREAD

**Issue by jianqixi** [LLNL/sundials#117]
Dear All,

I am trying to use the ARKODE solver for my problem, but I got one error when compiling my code, and it showed that:

error: too few arguments to function ‘_generic_N_Vector* N_VMake_Serial(sunindextype, realtype*, SUNContext)’
y0 = N_VMake_Serial(neq, y0data);

I am very curious about this error, because for the same command if I used CVODE solver, everything works well, but if I used ARKODE solver, this command will cause some errors.

I also read the manual of ARKODE, it seems like I do not need to have additional arguments for this command.

Thank you for your suggestions on my code.

In order to better know my issue, I have attached the main() of my code for your check. Thank you very much!

Sincerely,

Jianqi

*****************************************
int main(int argc, char* argv[]){
	realtype y0data[neq],t;
	double T0 = 0;      //initial time
	N_Vector y0 = NULL; //empty vector for storing solution
	UserData data = NULL;
	void *arkode_mem = NULL; //empty ARKode memory structure
	int flag,itask;
	

	//Create teh SUNDIALS context object for this simulation
	//SUNContext y0data;
	//flag = SUNContext_Create(NULL, &y0data);
	
	initParams();
	realtype *yd;
	realtype sum=0;
	getInitVals(y0data);	

	//SUNContext_Create();
	#ifdef _OPENMP
	num_threads = omp_get_max_threads();
	#endif
	cout<<"num_threads: "<<num_threads<<endl;

	//To set the vector y0 of initial values
	//y0 = N_VMake_OpenMP(neq, y0data, num_threads); //create and allocate memory for an openmp vector with supplied data array	
	y0 = N_VMake_Serial(neq, y0data); //creat and alllocate memory for a serial vector with supplied data array 
	if (check_flag((void *)y0, "N_VMake_Serial", 0)) return 1;

	realtype tout = 1E1; // modified time=fulence/flux; This is the final solution time.  The solver will solve for y0(t) on the range (0,tout)

	for (int i = 0; i < runs; i++) {
		cout << "T0 = " << T0 << endl;
		cout << "tout = " << tout << endl;	
		arkode_mem = ARKStepCreate(NULL, f, T0, y0, y0data);
		if (check_flag((void *)arkode_mem, "ARKStepCreate", 0)) return 1;

		data = (UserData) malloc(sizeof *data);
	     	loadData(data);
		// Set routines
		flag = ARKStepSetUserData(arkode_mem, data); //?????
		if (check_flag(&flag, "ARKStepSetUserData", 1)) return 1;
		
		flag = ARKStepSStolerances(arkode_mem, RTOL, ATOL);   // Specify tolerances
		if (check_flag(&flag, "ARKStepSStolerances", 1)) return 1;

		SUNMatrix A = SUNDenseMatrix(neq,neq, y0data);
		if (check_flag((void *)A, "SUNDenseMatrix", 0)) return 1;
		SUNLinearSolver LS = SUNLinSol_Dense(y0, A, y0data);
		if (check_flag((void *)LS, "SUNLinSol_Dense", 0)) return 1;

		flag = ARKStepSetLinearSolver(arkode_mem, LS, A);
		if (check_flag(&flag, "ARKStepSetLinearSolver", 1)) return 1;
		
		flag = ARKStepEvolve(arkode_mem, tout, y0, &t, ARK_NORMAL);
		if (check_flag(&flag, "ARKStepEvolve", 1)) break;

		//tout is the next time at which a computed solution is desired; &t is the time reached by the solver. tout is the maximum interval step, which is defined 
by the user, and &t is the step that the solver can reach. &t can be smaller than tout if some errors occur, otherwise, &t will be equal to tout.
		//
		getOutput(y0,radM,rhoC);	
		//yd = NV_DATA_OMP(y0);
		yd = NV_DATA_S(y0);
		
		T0 = tout;
		tout = tout + 100;
	}
	ARKStepFree(&arkode_mem);
	SUNLinSolFree(LS);
	SUNMatDestroy(A);
	N_VDestroy(y0);
	FreeUserData(data);
	delete data;
	return 0;
}

************************************************

**Comment by balos1** [comment]
What version of SUNDIALS are you using?

**Comment by jianqixi** [comment]
> 

Hi Cody, Thank you for your reply. The ARKODE version I am using is 5.1.1. Thank you
