### ISSUE TITLE
Example for the SDIRK

### ISSUE THREAD

**Issue by jianqixi** [LLNL/sundials#119]
Dear All,

I am wondering do we have some examples of the usage of SDIRK in the sundials? Any recommendations would be very appreciated.

**Comment by drreynolds** [comment]
Nearly every implicit example in ARKODE uses SDIRK methods.  In just the `examples/arkode/C_serial` folder alone there are: `ark_KrylovDemo_prec.c`, `ark_analytic.c`, `ark_brusselator.c`, `ark_brusselator1D.c`, `ark_brusselator1D_FEM_slu.c`, `ark_brusselator1D_klu.c`, `ark_heat1D.c`, `ark_heat1D_adapt.c`, `ark_robertson.c`, `ark_robertson_constraints.c`, and `ark_robertson_root.c`.

**Comment by jianqixi** [comment]
Thank you for your information.
