### ISSUE TITLE
Need of clarification about CVodeQuadSensInit 

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#121]
Hello,
In the documentation of cvodes about CVodeQuadSensInit (5.4.1), it is said that 
_If rhsQS is input as NULL, then cvodes uses an internal function that computes difference quotient approximations to the functions \bar q_i = q_ys_i+q_{p_i}..._ 
But in the workflow of steps 1..24 there is nothing to define the integrand q itself. From what it is said above, I may understand that when rhsQS =NULL the quadrature variable is implicitely defined as the derivative w.r.t. parameter p of the "regular" quadrature variable not depending on sensitivity (is it the case ?). However, I still do not understand where to define the integrand rhs when rhsQS =NULL. Maybe  CVodeQuadInit has to be called, but it is mentionned nowhere in the doc. 

Thanks for your explanations !

**Comment by mottelet** [comment]
Thanks, then is my affirmation

 _when rhsQS =NULL the quadrature variable is implicitely defined as the derivative w.r.t. parameter p of the "regular" quadrature variable not depending on sensitivity (hence defined by CVodeQuadInit)_

also true ?

**Comment by balos1** [comment]
Yes, that is right (see [5.2.6.4](https://sundials.readthedocs.io/en/latest/cvodes/Mathematics_link.html#quadratures-depending-on-forward-sensitivities)).

**Comment by mottelet** [comment]
OK I have read  5.2.6.4 already. However, I do not want to start a dialectic discussion (not being a native english speaker), but it seemed (to me) the only possible explanation, altghouh the sentence about the nullity of rhsQS does not clearly stated it.

**Comment by balos1** [comment]
This was fixed at some point. See https://sundials.readthedocs.io/en/latest/cvodes/Usage/FSA.html#c.CVodeQuadSensInit.

**Comment by mottelet** [comment]
Thanks !
