### ISSUE TITLE
usage of KLU

### ISSUE THREAD

**Issue by jianqixi** [LLNL/sundials#122]
Dear All, I have successfully installed KLU libraries with CVODE, and the ~/instrdir/include/ can also found the sunlinsol_klu.h. But when ran the code with #include <sunlinsol/sunlinsol_klu.h>, it shows the following errors:

/home/jianqi/sw/solvers/cvode-klu/instdir/include/sunlinsol/sunlinsol_klu.h:34:10: fatal error: klu.h: No such file or directory
 #include <klu.h>

Why it cannot find the klu.h? Do you have any idea about this? Thank you,

Jianqi

**Comment by mottelet** [comment]
You need to install SuiteSparse and also libsuitesparse-dev (which will provide all the headers, in particular klu.h).

S.

**Comment by mottelet** [comment]
Did it work for you (so that the staff could close the issue) ? 

S.
