### ISSUE TITLE
N_VMaxNorm_Sycl maximum workgroup-size exceeded

### ISSUE THREAD

**Issue by jonasbhjulstad** [LLNL/sundials#123]
I have modified the CVODE CXX_sycl-example provided with SUNDIALS to run on the cpu. 
(`sycl::gpu_selector selector` replaced with `  sycl::cpu_selector selector`, line 124) 
Compiling and running cvAdvDiff_kry_sycl.cpp with sycl enabled on the DPC++-compiler results in the following error:
```
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  The implementation handling parallel_for with reduction requires work group size not bigger than 4096 -54 (CL_INVALID_WORK_GROUP_SIZE)
Aborted (core dumped)
```
The error occurs upon calling N_VMaxNorm_Sycl, which seems to determine its workgroup-size using the input vector. 

Is it possible to configure the work group size from the interface of SUNDIALS?

**Comment by gardner48** [comment]
Yes, you can change this by creating a new [execution policy](https://sundials.readthedocs.io/en/latest/nvectors/NVector_links.html#the-sunsyclexecpolicy-class) and attaching it with [N_VSetKernelExecPolicy_Sycl](https://sundials.readthedocs.io/en/latest/nvectors/NVector_links.html#_CPPv427N_VSetKernelExecPolicy_Sycl8N_VectorP17SUNSyclExecPolicyP17SUNSyclExecPolicy) after constructing the initial condition vector ([line 136](https://github.com/LLNL/sundials/blob/736c0a9f1ec0bf58450a63ec1d8a6bd17f69b3fb/examples/cvode/CXX_sycl/cvAdvDiff_kry_sycl.cpp#L136)). CVODE uses this vector as a template to create other vectors internally via cloning and those vectors will use the same execution policy as the original vector.
