### ISSUE TITLE
Setting build options in 6.2.0 broken/problematic

### ISSUE THREAD

**Issue by becm** [LLNL/sundials#130]
When setting `ENABLE_PHREAD` the related `BUILD_NVECTOR_PTHREADS` is always set to `OFF`.
Log does not show any warning.

Similar behavior for `ENABLE_LAPACK`.
Not tested for further flags which have more complex dependencies, but this likely is an issue there as well.

Might be related to latest `sundials_option` [refactor](https://github.com/LLNL/sundials/commit/2953481772a0b562190ccd03fff99611e2096251).

To reporduce:
`cmake …`
`ccmake …` -> set `ENABLE_PHREAD` to `ON` (configure,generate)
check CMakeCache.txt for `BUILD_NVECTOR_PTHREADS` state.

Manual fiddling with CMakeCache.txt file (setting those options to `ON` and regenerate) results in expected build setup.

**Comment by gardner48** [comment]
@becm Thanks for reporting this regression when using `ccmake`. As you suspected the problem is in the updates to the `sundials_option` macro.  Note this bug in `sundials_option` only applies when using `ccmake` and does not impact `cmake` e.g., `cmake -DENABLE_PTHREAD=ON` will work as expected.
