### ISSUE TITLE
Very old versions archives no longer available

### ISSUE THREAD

**Issue by siko1056** [LLNL/sundials#133]
Recently all versions before SUNDIALS 3 seem to be no longer available.  For example:

https://github.com/LLNL/sundials/releases/download/v2.7.0/sundials-2.7.0.tar.gz, but https://github.com/LLNL/sundials/releases/tag/v2.7.0 exists.

How can one obtain this archive in the future to run and compare older versions?

**Comment by balos1** [comment]
@siko1056 Thanks for pointing this out. It was not our intention to remove those older versions. We will work to restore them.

**Comment by balos1** [comment]
@siko1056 In the meantime, you can download SUNDIALS 2.7.0 from here: https://github.com/sundials-codes/sundials-archive/releases/tag/v2.7.0

**Comment by balos1** [comment]
The [SUNDIALS 2.7.0 tag and download](https://github.com/LLNL/sundials/releases/tag/v2.7.0) has been fixed. Older versions must be obtained from https://computing.llnl.gov/projects/sundials/sundials-software.

**Comment by siko1056** [comment]
Thank you very much @balos1 for your quick help and fix.  It works now for me again 👍
