### ISSUE TITLE
Homebrew package with wrong open-mpi include path

### ISSUE THREAD

**Issue by mscuttari** [LLNL/sundials#150]
I'm running Monterey 12.4 on an M1 Pro and I've installed the sundials package through Homebrew. However, when importing the cmake target SUNDIALS::ida, I get the following error:

```
Imported target "SUNDIALS::ida" includes non-existent path
  "/opt/homebrew/Cellar/open-mpi/4.1.3/include"
in its INTERFACE_INCLUDE_DIRECTORIES. Possible reasons include:
* The path was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and references files it does not provide.
```

In the `/opt/homebrew/Cellar/open-mpi` folder I have only the 4.1.4 version, which has been installed automatically as a dependency while installing the sundials package.

**Comment by drreynolds** [comment]
I am sorry, @mscuttari, but the SUNDIALS team did not create, nor do we maintain, this Homebrew formula.  I recommend that you file an issue with Homebrew directly (https://github.com/Homebrew) so that they can fix this OpenMPI version issue.
