### ISSUE TITLE
Lapack Band vs KLU solver

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#158]
Hello, with a simple benchmark on the heat equation in a cube with finite differences, I noticed (under macOS/Intel) that with a 30x30x30 discretisation cvode is 3 times faster with the Lapack/band solver (with [n^2,n^2] bandwitdth and DQ jacobian than with KLU and exact sparse Jacobian. When looking at the cpu history I can see that the LapackBand solver uses all cores (likely during elimination and back substitution phase of linear solves), which is expected since Lapack on macOS uses Altivec instruction set. When using the KLU linear solver, only one core is used. Hence, I suppose that I should got for SuperLU_MT solver instead ?

S.

**Comment by balos1** [comment]
According to https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/32, KLU is only single threaded so, yes, you will need to use a different linear solver (that is multithreaded) if you want it to use multiple cores. SuperLU_MT would be the only sparse option without writing a custom SUNLinearSolver interface to another package (which is not too difficult either).
