### ISSUE TITLE
compile error on visual studio with /sdl option  sundials 5

### ISSUE THREAD

**Issue by phlptp** [LLNL/sundials#16]
I am pretty sure this is not an actual error since there are checks in place, but apparently not ones the compiler can detect. This issue currently prevents compilation of the 5.0 release on Visual Studio with the additional security checks enabled.
```
1>...\sundials\src\arkode\arkode_mristep.c(539): error C4703: potentially uninitialized local pointer variable 'inner_arkls_mem' used
```

If the pointers are initialized to NULL the error goes away.

**Comment by balos1** [comment]
5.0.0-dev.2 includes this fix.
