### ISSUE TITLE
SuperLU_DIST matrix interface constructor definition does not match declaration

### ISSUE THREAD

**Issue by balos1** [LLNL/sundials#169]
https://github.com/LLNL/sundials/blob/e2f29c34f324829302037a1492db480be8828084/src/sunmatrix/slunrloc/sunmatrix_slunrloc.c#L79

**Comment by balos1** [comment]
Missing the `SUNContext` argument

**Comment by gardner48** [comment]
The CI did not catch this because there's a typo in `test/config_cmake.py`. `ENABLE_SUPERLU_DIST` should be `ENABLE_SUPERLUDIST`.

**Comment by balos1** [comment]
Closed by #202
