### ISSUE TITLE
How to enable device-aware MPI?

### ISSUE THREAD

**Issue by stgeke** [LLNL/sundials#171]

**Comment by balos1** [comment]
This depends on the MPI implementation you are using. With OpenMPI, there has been some GPUDirect since v1.7.0 and newer versions have even better support.

**Comment by stgeke** [comment]
So you always pass GPU buffers to MPI? What if you want to run on GPUs but there is no GPU aware MPI?

**Comment by balos1** [comment]
There is no point-to-point communication within SUNDIALS itself, only reductions to a scalar on the CPU (e.g., for norms) so no GPU aware MPI is needed for this.  The point-to-point communication would only take place only in the user-supplied callbacks or possibly in external libraries for the linear solve (such as SuperLU_DIST). The obvious example of a user-supplied function is the right-hand-side function.  It is up to you how the GPU buffers are handled in this function.
