### ISSUE TITLE
Radau scheme

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#176]
Hello,

are there plans to implement the Radau schemes (particularly the variable order version) in Sundials ?

S.

**Comment by drreynolds** [comment]
I cannot comment on plans among the wider community, but I do not believe that anyone on our core team is planning these for the near future.  I am aware of some collaborators who were interested in creating/contributing a new ARKODE time-stepping module for fully implicit Runge--Kutta methods (like Radau), but I am uncertain of their progress.
