### ISSUE TITLE
Provide constraint function instead of projection function in CVODE

### ISSUE THREAD

**Issue by masoud-najafi** [LLNL/sundials#187]
Hi,
For IVPs with constraints, CVODE ensures that the solution satisfies constraint equations.  For that, the user should provide the projection function. My problem is that the projection function is not easy to obtain from the original constraint functions.
I wonder if there is a way to directly provide CVODE, the constraint function instead of the projection function?
Best regards,
Masoud

**Comment by gardner48** [comment]
Currently a user-supplied projection function is required. Adding an internal projection option would be a nice addition, but we don't currently have plans to do so. 

One option would be to implement a coordinate projection method as the user-supplied projection function. See [this section](https://sundials.readthedocs.io/en/latest/cvode/Mathematics_link.html#ivps-with-constraints) in the user guide for the general idea. Alternatively, if you do not need to satisfy the constraint exactly but instead to within some tolerance, you might want to consider using IDA to solve the DAE system.
