### ISSUE TITLE
Static Analysis Identifies 821 Potential Issues

### ISSUE THREAD

**Issue by arrieta** [LLNL/sundials#2]
Our continuous integration pipeline performs static analysis on all source code. As we integrated SUNDIALS into one of our projects, the static analysis on the sources identified 821 potential issues:

|Issue Kind|Count|
|---|---|
|Dead assignment|323|
|Dereference of null pointer|152|	
|Result of operation is garbage or undefined|18|
|Uninitialized argument value|23|
|Leak|9|
|Memory leak|282|
|Allocator sizeof operand mismatch|14|	
|**Total**|821|	

The typical pattern for null pointer dereference (the more concerning case) is as follows:

```
while (IDAB_mem != NULL) {
    if( which == IDAB_mem->ida_index ) break;
    IDAB_mem = IDAB_mem->ida_next;
}  
N_VScale(ONE, IDAB_mem->ida_yy, yy);
```

In the above pattern (observed in line 1549 of file `src/idas/idaa.c`) we see that when `IDAB_mem` is in fact `NULL`, execution will proceed directly to `N_VScale(ONE, IDAB_mem->ida_yy, yy)`, resulting in a dereference of null pointer. All 821 issues are described in detail in https://www.nablazerolabs.com/sundials/.

**Comment by gardner48** [comment]
Hi Juan, thanks for reporting these issues. Some of the items in your report are addressed in the upcoming 3.1.1 release and we'll work on resolving the remainder in follow-on patch releases.

**Comment by arrieta** [comment]
My pleasure. I look forward to the upcoming releases.

**Comment by balos1** [comment]
Lots of code has been modified and added since this was open. Closing now.
