### ISSUE TITLE
Different behavior of CVODE depending on dense linear solver

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#204]
Hello,

The following simple case (heat equation in a cube with finite differences: [suncube.c.zip](https://github.com/LLNL/sundials/files/9674774/suncube.c.zip)) fails when SUNLinSol_LapackDense  is used instead of SUNLinSol_Dense:
````
Dense, retval=0

[CVODE ERROR]  CVode
  At t = 0 and h = 1.16215e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

Lapack Dense, retval=-4
````
How can it be ?

**Comment by mottelet** [comment]
I recompiled SUNDIALS library with `SUNDIALS_INDEX_SIZE=32` and it solved the problem.

**Comment by balos1** [comment]
Some of the solvers can be built with either `SUNDIALS_INDEX_SIZE=32` or `SUNDIALS_INDEX_SIZE=64`.  Here is a list of the few constraints off the top of my head:

- The `cuSolverSp` linear solver requires 32-bit indices
- The Xbraid parallel in time feature requires 32-bit indices
- The `oneMKL` dense linear solver requires 64-bit indices
- The Fortran 2003 interfaces require 64-bit indices

Most everything else should support 32 or 64-bit indices, but it is important to make sure that the third-party library and SUNDIALS are built with compatible index sizes. Usually the CMake will error out if they do not match as we try to check.
