### ISSUE TITLE
Incorrect function name in doc

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#206]
In table 4.7 in cvode online doc (https://sundials.readthedocs.io/en/latest/cvode/Usage/index.html#id13) one can read

_No. of calls to r.h.s. function | CVodeGetNumLinSolvSetups()_

instead of 

_No. of calls to r.h.s. function | CVodeGetNumRhsEvals()_

the link is also incorrect.

**Comment by balos1** [comment]
@mottelet Thanks for reporting!

**Comment by balos1** [comment]
Closed by #208
