### ISSUE TITLE
KINInit leaks memory on successive calls

### ISSUE THREAD

**Issue by mcneish1** [LLNL/sundials#22]
Calling KINInit more than once in a particular context leaks memory.

KINInit calls KINAllocVectors here:
https://github.com/LLNL/sundials/blob/4270cd115373268df6585a2db4053fadb4bf79e8/src/kinsol/kinsol.c#L341

which in turn assigns to `kin_unew` here:
https://github.com/LLNL/sundials/blob/4270cd115373268df6585a2db4053fadb4bf79e8/src/kinsol/kinsol.c#L716

without checking whether `kin_unew` was previously assigned.  This causes the `N_Vector` `kin_unew` held from the previous init to be leaked.

It appears that a call to `KINFreeVectors` in the prologue of `KINAllocVectors` will catch this and be safe, except potentially https://github.com/LLNL/sundials/blob/4270cd115373268df6585a2db4053fadb4bf79e8/src/kinsol/kinsol.c#L954-L955 which are not covered by a null check.

(related to https://github.com/LLNL/GridDyn/issues/53)

**Comment by gardner48** [comment]
@mcneish1 Thanks for bringing this to our attention. As you noted in the GridDyn issue KINInit should only be called once in which case these leaks would not occur. That said we do want to guard against this happening and the 5.1.0 release adds a check to see if an NVector has already been allocated before making a clone.
