### ISSUE TITLE
4 tests fail

### ISSUE THREAD

**Issue by yurivict** [LLNL/sundials#220]
[sunddials-tests.log.bz2.REMOVE-ME.txt](https://github.com/LLNL/sundials/files/9845107/sunddials-tests.log.bz2.REMOVE-ME.txt)

**Comment by yurivict** [comment]
The attached file is a compressed log with all failure details. Just rename it sunddials-tests.log.bz2.REMOVE-ME.txt to sunddials-tests.log.bz2 and uncompress.

Please let me know what other details do you need.

Version: 6.4.0
sundials is built from the port
OS: FreeBSD 13.1 STABLE
compiler: clang-14

**Comment by balos1** [comment]
@yurivict this should be fixed by #223.

**Comment by yurivict** [comment]
I'll retest with the next sundials release.
Thanks for fixing it.

**Comment by balos1** [comment]
Closed by #223.
