### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by artgoldberg** [LLNL/sundials#24]
The links to Documentation in `https://github.com/LLNL/sundials/blob/master/src/cvode/README.md` don't point to the right files. I found them nonetheless.

**Comment by gardner48** [comment]
@artgoldberg Thanks for bringing this to our attention. I've updated the links in our development repo and the changes will be included in the next patch release.

**Comment by gardner48** [comment]
These links have been fixed in the 5.1.0 release.
