### ISSUE TITLE
Package missing in EPEL 9

### ISSUE THREAD

**Issue by sffc** [LLNL/sundials#244]
I've always installed the `sundials-devel` RPM from the EPEL package repository. However, it seems to be missing from the latest repo, EPEL 9:

https://pkgs.org/search/?q=sundials-devel

It shows up only in EPEL 7 and EPEL 8. Note that it is still listed on Fedora.

Could `sundials-devel` be added to EPEL 9? I'm not sure the right place to open this issue.

P.S. I need it in order to build GNU Octave.

**Comment by balos1** [comment]
Hi @sffc The sundials team does not maintain the RPM. You can check https://packages.fedoraproject.org/pkgs/sundials/sundials-devel/index.html to see who maintains it and reach out to them.

**Comment by sffc** [comment]
Thanks for the pointer. Filed another bug: https://bugzilla.redhat.com/show_bug.cgi?id=2156966

**Comment by sundials-users-github-account** [comment]
Hello everyone.

I am having the same problem as described here:

https://groups.google.com/g/sundials-users/c/Img7moAvhxI/m/CBq0zDSqBQAJ


 except it not ocorred in function idm ( [varargout{:}] =
idm(mode,tout,itask)) but in function cvm  ( [varargout{:}] =
cvm(mode,tout,itask) ).

The message is: "Error using idm; Requested 8589934602x1x73269248
(4689231877.5GB) array exceeds maximum array size preference. Creation of
arrays greater than this limit may take a long time and cause MATLAB to
become unresponsive. See array size limit or preference panel for more
information."

Does someone have any ideas for solving this problem?


Thanks a lot.


Luiz
