### ISSUE TITLE
`SUNMatScaleAdd_Sparse` has time complexity O(M*N)

### ISSUE THREAD

**Issue by phannebohm** [LLNL/sundials#253]
As the title says, adding two sparse matrices scales badly. I believe the problem are loops like the sparsity pattern overlap check here:
https://github.com/LLNL/sundials/blob/7c318244182061ea482b449bdb5a14d4d3c71e57/src/sunmatrix/sparse/sunmatrix_sparse.c#L827-L832

Just filling the work array `w` with zeros takes M*N operations. This happens in a few places inside this function with `w` and `x`. If I replace the for loops with calls to `memset` I save a significant amount of computation time (maybe 75% on my machine, don't trust that number though). However it still scales badly. I would expect addition to scale like O(NNZ) instead.

On a side note, for my particular use case (OpenModelica/OpenModelica#10178) I can take a modified version of `SUNMatScaleAddI_Sparse`, I call it `SUNMatScaleIAdd_Sparse` where the result is $A + c I$. This scales linearly as expected. Perhaps this function could be useful for other people.

**Comment by balos1** [comment]
Thanks for noting this. Indeed this is because the current implementation support a very general case. Perhaps we can add an option (controlled with a Set function) to use less general, but faster implementations of `ScaleAdd` and `ScaleAddI`.

**Comment by phannebohm** [comment]
I think I have a general solution that avoids these scaling issues, at least for `ScaleAddI`. I can open a PR for it and see if it can also be ported to `ScaleAdd`.

**Comment by balos1** [comment]
Closed by #257.
