### ISSUE TITLE
CVode root finding function: infinite loop 

### ISSUE THREAD

**Issue by guibou** [LLNL/sundials#258]
Hello dear sundial maintainers.

I observed that the root finder of cvode leads to an infinite loop if the function we are finding root for returns `NaN` (Not a Number).

# Code details

The code in:

https://github.com/LLNL/sundials/blob/main/src/cvode/cvode.c#L4213

breaks the loop or exit the function in the following conditions:

- `retval != 0`, this only happen if the function evaluated return a non zero status, as documented in https://sundials.readthedocs.io/en/latest/cvode/Usage/index.html#c.CVRootFn "A CVRootFn should return 0 if successful or a non-zero value if an error occured (in which case the integration is haled and CVode returns CV_RTFUNC_FAIL."
- `zroot`, which implicitely depends on `cv_mem->cv_rootdir[i]*cv_mem->cv_glo[i] <= ZERO`.
- `SUNRabs(cv_mem->cv_thi - cv_mem->cv_tlo) <= cv_mem->cv_ttol`: the convergence critira is achieved.

In a `NaN` is returned in the function (i.e. in `cv_mem->cv_grout`), then it wil be propagated to `cv_ghi`, or `cv_glo`, which ends propagating to most of the floating point value in the loop.`

Because of the proporties of `NaN`, all of the above tests are always `false`, leading to never exiting the loop.

# My issue

I had this problem in our code in production, one sundial process never terminated.

I observed using `perf top` that sundials was taking all the time:

```
  19.39%  simwork.core-:w  libsundials_arkode.so.5.4.1                                    [.] Vaxpy_Serial.isra.0                                                                               
  17.02%  simwork.core-:w  libsundials_cvode.so.6.4.1                                     [.] cvRcheck3                                                                                         
  10.53%  simwork.core-:w  libsundials_cvode.so.6.4.1                                     [.] CVodeGetDky                                                                                       
   8.52%  simwork.core-:w  libsundials_arkode.so.5.4.1                                    [.] N_VScale_Serial                                                                                   
   4.52%  simwork.core-:w  libsundials_arkode.so.5.4.1                                    [.] N_VLinearCombination                                                                              
   3.39%  simwork.core-:w  [JIT] tid 126223                                               [.] 0x00007f22a7e33007                                                                                
   1.73%  simwork.core-:w  libsundials_arkode.so.5.4.1                                    [.] N_VLinearSum_Serial     
```

Luckily, I do have an alternative solving method: my `CVRootFn` can be implemented using JIT in machine code, or using a high level Haskell implementation. Running the Haskell implementation crashed in my root function (i.e. my Haskell code detects NaN and crashs), so I quickly understood the problem was due to a NaN, I fixed my JIT code to return non zero value in `CVRootFn` and after confirming that the problem was in the root function, I was able to step debug in sundial to understand the reason of the infinite loop.

# Discussion / solution

I was "lucky" I had an alternate implementation which allowed me to find the problem (which is in my code), but I was wondering if sundials should not be made more robust for this kind of user error.

For the record, I added the following code in our codebase in a defensive way:

```diff
diff --git a/src/cvode/cvode.c b/src/cvode/cvode.c
index f7e00ce74..349483ba0 100644
--- a/src/cvode/cvode.c
+++ b/src/cvode/cvode.c
@@ -4078,6 +4078,19 @@ static int cvRcheck3(CVodeMem cv_mem)
   return(RTFOUND);
 }
 
+static booleantype sunIsNaN(sunrealtype a)
+{
+#if defined(__cplusplus) || defined(SUNDIALS_C_COMPILER_HAS_ISINF_ISNAN)
+  return(isnan(a));
+#else
+  /* Most compilers/platforms follow NaN != a,
+   * but since C89 does not require this, it is
+   * possible some platforms might not follow it.
+   */
+  return(a != a);
+#endif
+}
+
 #define DIFFERENT_SIGN(a,b) ( ( (a) < 0 && (b) > 0 ) || ( (a) > 0 && (b) < 0 ) )
 
 /*
@@ -4211,6 +4224,10 @@ static int cvRootfind(CVodeMem cv_mem)
 
   side = 0;  sideprev = -1;
   for(;;) {                                    /* Looping point */
+      if(sunIsNaN(tmid))
+            return(CV_RTFUNC_FAIL);
+
 ```

I copied the `sunIsNaN` implementation from elsewhere in the codebase, this can be factorized too.

# Conclusion

I mostly opened this issue for reference for future users who may have infinite loop in the cvode code.

What are your points of view regarding this problem? Would you accept MR adding sanity check on the output of the function?

**Comment by drreynolds** [comment]
I have some reservations with forcing this check for all users who ever enable root-finding, as it might slow down everyone's simulations just to capture a rare error within a user-supplied function.  That said, I like the idea of supporting safeguards to help users track down errors.  I can think of two options that might work:
1. Leave SUNDIALS as-is, but add some clear warnings to the documentation that the root-finding feature will fail if the user function returns NaN, and so concerned users should test for NaN in the output of their root-finding function itself.  We could even export the `sunIsNaN` function so that it is accessible to users, allowing them to call this within their root-finding function. 
2. Add this in as a compile-time option, e.g., using an `#ifdef`.  This would be disabled by default, but users could enable this protection if desired.

**Comment by guibou** [comment]
@drreynolds 

1. good point about the documentation, I'll try to allocate a bit of time to update the documentation.
2. I don't know what is the sundial policy about compile time option for additional checks, but from my experience, users are rarely using them as first approximation.

**Comment by drreynolds** [comment]
I agree about 2, and even as I wrote those ideas I was leaning towards 1.  I'll discuss exporting `sunIsNaN` in our developer meeting next week (most are on travel right now at a conference).

**Comment by balos1** [comment]
It was decided to leave this as-is, but it is a good reference for users who run into this problem in the future.  We will also be updating our documentation in the future to have a "common issues" section for stuff like this.
