### ISSUE TITLE
IDASetStopTime cannot be reversed

### ISSUE THREAD

**Issue by gfrontera** [LLNL/sundials#262]
When setting _tstop_ with `IDASetStopTime()`, there is no way to unset it manually. If said _tstop_ does not trigger the following call to `IDASolve()` to stop, it will remain set, even when `IDAReInit()` has been called.

This is a well documented behavior, but after a call to `IDAReInit()`, the program is usually solving a completely different problem and the previously set _tstop_ does not make sense and triggers unwanted errors. If `IDAReInit()` does not unset _tstop_, there should be a way to manually unset it.

**Comment by balos1** [comment]
@gfrontera Can you explain your use case more? I am trying to understand what you are using the stop time for and why is it not being reached, and then why do you not need the stop time after the ReInit.

**Comment by balos1** [comment]
Fixed by #264.

**Comment by gfrontera** [comment]
> @gfrontera Can you explain your use case more? I am trying to understand what you are using the stop time for and why is it not being reached, and then why do you not need the stop time after the ReInit.

Sorry I didn't reply in time, I didn't see your request until now. Glad find out it's done! Thanks!
