### ISSUE TITLE
Minor nitpick: KINGetNumLinFuncEvals exported twice

### ISSUE THREAD

**Issue by bjodah** [LLNL/sundials#28]
see here:

https://github.com/LLNL/sundials/blob/b78e575639babe99aea9a0558d0f64732d6d729e/include/kinsol/kinsol_ls.h#L96

and here:
https://github.com/LLNL/sundials/blob/b78e575639babe99aea9a0558d0f64732d6d729e/include/kinsol/kinsol_ls.h#L108

all the best,
Björn

**Comment by gardner48** [comment]
Thanks @bjodah for pointing this out. I've fixed this in our development repo and the update will be included in the next release.
