### ISSUE TITLE
Error in doc for CVodeGetQuad prototype

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#280]
The doc (https://sundials.readthedocs.io/en/latest/cvodes/Usage/SIM.html#c.CVodeGetQuad) says

![Screenshot 2023-06-07 at 19 14 33](https://github.com/LLNL/sundials/assets/8794797/d2c2e2ad-136d-4fe6-8a97-57c93459c220)

a "*" is missing before "realtype".

S.

**Comment by balos1** [comment]
@mottelet Thanks! When we moved from LaTex to rst/sphinx the tools we used likely made some mistakes like these and we then missed them. It is helpful to have someone point out the errors as they see them, so your reports are very appreciated.

**Comment by mottelet** [comment]
I think that are many other issues of this type. I just encountered two others in cvs_guide.pdf and in the online documentation:
![Capture d’écran 2023-06-12 à 13 29 15](https://github.com/LLNL/sundials/assets/8794797/8caa1dab-7d69-4295-b178-36a4c297bf9c)
![Capture d’écran 2023-06-12 à 13 29 21](https://github.com/LLNL/sundials/assets/8794797/2a605c68-63cc-4450-b3dc-a942523f0889)
i.e. `realtype` instead of `realtype ` for `tret`.

**Comment by mottelet** [comment]
Other issues:

![Capture d’écran 2023-06-14 à 10 27 39](https://github.com/LLNL/sundials/assets/8794797/726cf0d7-eed6-46d6-98cf-37967e65ee79)
![Capture d’écran 2023-06-14 à 10 26 58](https://github.com/LLNL/sundials/assets/8794797/f00409d5-520e-4747-87fd-08fd90cd02be)
actual proto is `int CVodeQuadSVtolerances(void *cvode_mem, realtype reltolQ, N_Vector abstolQ)`

**Comment by balos1** [comment]
Closed by #295.
