### ISSUE TITLE
README in v2.7.0 tag contains wrong version

### ISSUE THREAD

**Issue by hgossler** [LLNL/sundials#3]
The README file in tag v2.7.0 refers to v2.6.2 of August 2015. Is it just the README that's wrong, or should this be in fact tagged as v2.6.2?

Thanks!

**Comment by gardner48** [comment]
Thanks for bringing this to our attention. The v2.7.0 tag is correct and it's the version number at the top of the README file that's wrong. The table of releases at the bottom of the README file list the correct version number and release date (2.7.0, September 2016).
