### ISSUE TITLE
Support for BLAS/LAPACK ABIs with `64_` suffix

### ISSUE THREAD

**Issue by ViralBShah** [LLNL/sundials#30]
Julia ships with openblas (w/lapack) compiled to have the suffix `64_` in the 64-bit case. This is a convention that many libraries have started adopting. It would be great for the sundials build to provide this name mangling option.

Currently we carry this patch for fortran: 
https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/Sundials%405/bundled/patches/Sundials_Fortran.patch

**Comment by balos1** [comment]
I like the idea of handling this with a CMake option like `SUNDIALS_F77_FUNC_UNDERSCORES` or `SUNDIALS_F77_FUNC_CASE`. I think we would probably allow a custom suffix to be set rather than having the `64_` specifically.

**Comment by gardner48** [comment]
@balos1 I agree it would be good to to have separate the macros for the F77 interfaces and LAPACK. It does happen (though I've not run into it before) that the LAPACK name mangling is different for the Fortran name mangling. I know hypre and PETSc both provide an option to set a different name mangling scheme for LAPACK. A separate macro/option would also allow for providing a scheme even when a Fortran compiler is not present.
