### ISSUE TITLE
Examples cannot be compiled

### ISSUE THREAD

**Issue by johnwparent** [LLNL/sundials#330]
https://github.com/LLNL/sundials/blob/main/examples/utilities/example_utilities.hpp#L89 references the method `stoi` which is declared in the system `<string>`. This file does not include `<string>` and as such cannot be compiled.
 
Tested on:
| ------------- | ------------- |
| Platform  | Windows  |
| Compiler |  MSVC 19.29.30145  |
| Generator |  Ninja      |
| CMake Args |   -DBUILD_CVODE:BOOL=ON -DBUILD_CVODES:BOOL=ON -DBUILD_ARKODE:BOOL=ON -DBUILD_IDA:BOOL=ON -DBUILD_IDAS:BOOL=ON -DBUILD_KINSOL:BOOL=ON -DCMAKE_C_STANDARD:STRING=99 -DCMAKE_CXX_STANDARD:STRING=14 -DSUNDIALS_PRECISION:STRING=double -DSUNDIALS_INDEX_SIZE:STRING=32 -DSUNDIALS_INDEX_TYPE:STRING=int32_t -DF77_INTERFACE_ENABLE:BOOL=OFF -DF2003_INTERFACE_ENABLE:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=ON -DUSE_GENERIC_MATH:BOOL=ON -DSUNDIALS_LOGGING_LEVEL:STRING=0 -DSUNDIALS_LOGGING_ENABLE_MPI:STRING=OFF -DSUNDIALS_BUILD_WITH_MONITORING:BOOL=OFF -DSUNDIALS_BUILD_WITH_PROFILING:BOOL=OFF  -DMPI_ENABLE:BOOL=ON -DOPENMP_ENABLE:BOOL=OFF -DPTHREAD_ENABLE:BOOL=OFF -DENABLE_SYCL:BOOL=OFF -DCUDA_ENABLE:BOOL=OFF -DENABLE_HIP:BOOL=OFF -DHYPRE_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DPETSC_ENABLE:BOOL=OFF -DRAJA_ENABLE:BOOL=OFF -DSUPERLUMT_ENABLE:BOOL=OFF -DSUPERLUDIST_ENABLE:BOOL=OFF -DTrilinos_ENABLE:BOOL=OFF -DENABLE_KOKKOS:BOOL=OFF -DENABLE_KOKKOS_KERNELS:BOOL=OFF -DEXAMPLES_INSTALL:BOOL=ON -DEXAMPLES_ENABLE_C:BOOL=ON -DEXAMPLES_ENABLE_CXX:BOOL=ON -DEXAMPLES_ENABLE_CUDA:BOOL=OFF -DEXAMPLES_ENABLE_F77:BOOL=OFF -DEXAMPLES_ENABLE_F90:BOOL=OFF -DEXAMPLES_ENABLE_F2003:BOOL=OFF              |

Note: this build was originally driven from Spack and then reproduced by hand using the CMake command line above.

**Comment by balos1** [comment]
Closed by #331. Thanks for the contribution.
