### ISSUE TITLE
Question about API uses (CVLsJacFn)

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#338]
Hello, the prototype of `CVLsJacFn`
```
typedef int (*CVLsJacFn)(realtype t, N_Vector y, N_Vector fy,
                         SUNMatrix Jac, void *user_data,
                         N_Vector tmp1, N_Vector tmp2, N_Vector tmp3);
```
considers cases where the actual value of the rhs `fy` can be used for the computation of the Jacobian. Do you have examples where this is actually useful (and thus saves a recomputation of the rhs) ?

**Comment by gardner48** [comment]
This input is used by the internal functions to compute finite difference Jacobian approximations and could similarly be used in user-supplied Jacobian functions in computing an approximation.

**Comment by mottelet** [comment]
OK. In this particular situation it saves one rhs call right ?

**Comment by drreynolds** [comment]
Yes.  Since the current rhs is available, we pass it through this function call purely so that it can be reused instead of recomputed.
