### ISSUE TITLE
Memory leak in CVodeSensSVtolerances

### ISSUE THREAD

**Issue by krtab** [LLNL/sundials#34]
Hi! Thanks for developing this package.

I have a program calling sundials and valgrind tells me it is leaking memory. After building sundials with the debug symbols, this line seems to be the culprit:

https://github.com/LLNL/sundials/blob/b78e575639babe99aea9a0558d0f64732d6d729e/src/cvodes/cvodes.c#L2152

And indeed, it seems to me there is no free of "cv_atolSmin0".

Let me know if you need any more help.

**Comment by gardner48** [comment]
@krtab you're correct this array is not freed nor is the `cv_atolQSmin0` array. These same leaks are also in IDAS. This [patch](https://github.com/LLNL/sundials/files/4335917/free-atolSmin0-and-atolQSmin0.txt) fixes the leaks in CVODES and IDAS and will be included in the next release.

**Comment by krtab** [comment]
Wow! Thanks a lot for this swift response. :)

**Comment by krtab** [comment]
Do you have an estimate for when you plan to release it ?

**Comment by gardner48** [comment]
@krtab we don't have a specific date set for the next minor release but I anticipate it should be available in next few weeks.

**Comment by balos1** [comment]
@krtab The release with this fix is now available.
