### ISSUE TITLE
Documentation issue 

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#340]
At page
https://sundials.readthedocs.io/en/latest/cvodes/Usage/SIM.html#c.CVodeQuadSVtolerances
the documentation is supposed to describe CVodeQuadSVtolerances but mentions CVodeQuadSStolerances on the second line and further. For example it is said that abstolQ is a scalar although it should be a N_Vector.
Second point : CVodeQuadSStolerances is not mentioned in the documentation.

**Comment by balos1** [comment]
Fixed by #352.
