### ISSUE TITLE
sundials/sundial.context.h not found

### ISSUE THREAD

**Issue by baluniranjanofficial** [LLNL/sundials#342]
I am installing sundial 5.1.0, which is a dependency for installing scikits.odes package.
Sundial installation is finishing successfully.
But when I try to install scikits.odes pacakage, it shows that sundials/sundial.context.h is not found.

I am sharing a part of the error that comes.

      Warning: ‘index’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      INFO: /usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-cpython-39/build/src.linux-x86_64-3.9/scikits/odes/lsodimodule.o build/temp.linux-x86_64-cpython-39/build/src.linux-x86_64-3.9/build/src.linux-x86_64-3.9/scikits/odes/fortranobject.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/lsodi.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/xerrwv.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/daux.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/ewset.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/intdy.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/dlinpk.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/ddaspk.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/cfode.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/solsy.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/vnorm.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/ainvg.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/stodi.o build/temp.linux-x86_64-cpython-39/scikits/odes/daepack/prepji.o build/temp.linux-x86_64-cpython-39/build/src.linux-x86_64-3.9/scikits/odes/lsodi-f2pywrappers.o -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/local/lib -lgfortran -o build/lib.linux-x86_64-cpython-39/scikits/odes/lsodi.cpython-39-x86_64-linux-gnu.so
      INFO: building 'scikits.odes.sundials.common_defs' extension
      INFO: compiling C sources
      INFO: C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
      creating build/temp.linux-x86_64-cpython-39/scikits/odes/sundials
      INFO: compile options: '-I/tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.9/numpy/distutils/include -I/usr/local/include/python3.9 -c'
      extra options: '-msse -msse2 -msse3'
      INFO: gcc: scikits/odes/sundials/common_defs.c
      In file included from /tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from scikits/odes/sundials/common_defs.c:785:
      /tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      scikits/odes/sundials/common_defs.c:794:10: fatal error: sundials/sundials_context.h: No such file or directory
        794 | #include "sundials/sundials_context.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-85f8tz3w/overlay/lib/python3.9/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.9/numpy/distutils/include -I/usr/local/include/python3.9 -c scikits/odes/sundials/common_defs.c -o build/temp.linux-x86_64-cpython-39/scikits/odes/sundials/common_defs.o -MMD -MF build/temp.linux-x86_64-cpython-39/scikits/odes/sundials/common_defs.o.d -msse -msse2 -msse3" failed with exit status 1
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : gcc
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[863] : write cache to path -> /tmp/pip-install-pc8yzzfr/scikits-odes_9b2ffa07d3cf4e81a3f8e16f7dea4688/build/temp.linux-x86_64-cpython-39/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikits.odes
Failed to build scikits.odes
ERROR: Could not build wheels for scikits.odes, which is required to install pyproject.toml-based projects

Note : All other dependencies for installing scikits.odes also has been installed.
I used https://medium.com/theta-hat/installing-sundials-equation-solvers-on-ubuntu-4178da3258f4 to install sundials. But instead of 6.5.1 I installed 5.1.0.
[scikits.odes error.txt](https://github.com/LLNL/sundials/files/12643031/scikits.odes.error.txt)

I am attaching the error log also.

Thanks in advance :)

**Comment by gardner48** [comment]
@baluniranjanofficial scikits.odes moved to requiring sundials 6.x (see bmcage/odes#144) but the documentation has not been updated accordingly. I suggest opening an issue or submitting a PR to scikits.odes [GitHub repo](https://github.com/bmcage/odes) to update the installation instructions.
