### ISSUE TITLE
Update to uses-sundials page

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#354]
Hello,
The new official release of Scilab has integrated almost all SUNDIALS solvers (see https://help.scilab.org/section_8627f1cd274f2e03a5249666b62ade79.html) and in the page https://computing.llnl.gov/projects/sundials/uses-sundials the mention to the now deprecated sci-sundials toolbox should be replaced by a link to Scilab itself (http://www.scilab.org).
Besides the ease of being able to use the SUNDIALS machinery from one place with a script language, some features of the Scilab interface are the use of ColPack algorithms (https://cscapes.cs.purdue.edu/coloringpage/) to approximate sparse Jacobians given their sparsity pattern, the possibilities of solvers to consider complex/not real problems and to output solution interpolators which can be used as usual functions. Existing SUNDIALS rhs C code can also be interfaced to Scilab by dynamic link (examples are provided). This interface has been developed in the name of UTC (http://www.utc.fr).

I let you free to add or not to add details about the interface.

Thanks in advance.

**Comment by balos1** [comment]
Thanks for the update @mottelet. The change should go live on the SUNDIALS web page later today.

**Comment by mottelet** [comment]
Thanks !
