### ISSUE TITLE
Missing check if preconditioner for matrix-free linear solver is set

### ISSUE THREAD

**Issue by AnHeuermann** [LLNL/sundials#36]
## Problem
I run into a problem with the matrix-free linear solvers like `SUNLinSol_SPFGMR`. Basically I had chosen the wrong preconditioner setting `PREC_LEFT` and didn't supply a preconditioner function with `IDASetPreconditioner()`.
Since the error only showed while solving the linear system (in my case inside `IDASolve()`) I had to search for the problem for some time.

## Suggested solution
So would it be a good idea to add a small check for `NULL` somewhere after the call to `SUNLinSol_SPGMR(y, PREC_NONE, 5);`?

Or alternatively add a small check in `SUNLinSolSolve_SPGMR()` in [sunlinsol_spgmr.c](https://github.com/LLNL/sundials/blob/master/src/sunlinsol/spgmr/sunlinsol_spgmr.c#L462) to test if `psolve` is NULL and return an error flag.

For the other matrix-free linear solvers this applies as well.

**Comment by gardner48** [comment]
@AnHeuermann thanks for reporting this issue. We've added checks in the iterative linear solver modules to ensure the preconditioner solve function is non-NULL when preconditioning is enabled. This update will be included in the next release.
