### ISSUE TITLE
Can I use SUNDIALS as simulink solver?

### ISSUE THREAD

**Issue by LeXu1327** [LLNL/sundials#388]
Hi all,
I have a question, Can I use SUNDIALS as simulink solver?
Typically, we choose ode45 or ode15s as simulink solver. Can I use SUNDIALS (i.e., IDAs) instead?

Thanks！

**Comment by balos1** [comment]
SUNDIALS does not have a current MATLAB interface, so you would need to interface to the C code from MATLAB/simulink. There was a recent question along these lines on the SUNDIALS mailing list that may be of help to you https://groups.google.com/g/sundials-users/c/zceYQd1wVs4/m/wrWgPI1MBQAJ.
