### ISSUE TITLE
Sundials using all of the available GitHub Actions CI/CD runners

### ISSUE THREAD

**Issue by nightlark** [LLNL/sundials#393]
I think this is the second time that I've noticed that CI jobs in several other LLNL GitHub repositories that usually take a minute or two to run to completion have been blocked for 1+ hours until Sundials works its way through a large queue of CI builds.

From the looks of it, I think we may be on the lowest tier [free plan](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration) which only gives 20 concurrent jobs (with 5 concurrent macOS jobs) across the entire LLNL GitHub org -- a single Sundials CI job seems to have a build matrix that uses up 15-19 of those jobs, which quickly eats up the entire capacity when multiple commits/PRs are updated.

GitHub Actions supports a [concurrency group](https://docs.github.com/en/actions/using-jobs/using-concurrency) feature that can be used to limit the number of concurrent workflow runs. I think by applying the feature at the workflow file level the number of jobs could be limited to 10-15 runners being consumed by Sundials, enabling other repositories to also make at least some progress on their CI builds, though at a reduced rate.

**Comment by balos1** [comment]
@nightlark Thanks for the bringing this up, I was not aware that the GitHub Actions runners were shared across the LLNL GitHub org. I'll see about using the concurrency group feature to limit the number of concurrent workflow runs until a better solution is figured out.

**Comment by balos1** [comment]
I've disabled some of our workflows for the moment as we have unusually high development activity right now. [This change](https://github.com/LLNL/sundials/commit/d27f9e5a9fef98b80c4c18b90f8f02a2b53ccd94) to our concurrency group seems to be helping some too.
