### ISSUE TITLE
Install prefix

### ISSUE THREAD

**Issue by fertinaz** [LLNL/sundials#4]
Trying to install sundials-3.1.2 on my CentOS workstation but it fails with the following msg:
```
CMake Error at cmake_install.cmake:36 (FILE):
  file cannot create directory: /usr/local/include/sundials.  Maybe need
  administrative privileges.
```
I know this is self-explanatory but what I don't understand is that I am declaring install prefix in my $HOME directory. This is the build script I've written:
```
#!/bin/sh

#Package details
base=$HOME/sundials
pkg=sundials
vrs=3.1.2

#Go to sundials base folder
cd $base

#Environment variables
export srcdir=$base/$pkg-$vrs
export instdir=$base/$pkg-$vrs-install
export builddir=$base/$pkg-$vrs-build

#Do not build in-source
mkdir -p $builddir
cd $builddir

#Build
cmake \
  --DCMAKE_INSTALL_PREFIX=$instdir \
  --DMPI_ENABLE=ON   \
  --DHYPRE_ENABLE=ON \
  --DHYPRE_INCLUDE_DIR=${HYPRE_ROOT}/include \
  --DHYPRE_LIBRARY_DIR=${HYPRE_ROOT}/lib     \
  $srcdir

#Compile and install
make
make test
make install
```

I came across this old thread as I was looking for a workaround:
http://sundials.2283335.n4.nabble.com/The-lighter-side-of-SUNDIALS-td3239773i20.html

Is this really intentionally designed or somehow a bug? What is your suggestions?

**Comment by gardner48** [comment]
In the cmake configuration lines change ```--D``` to ```-D``` and that should resolve the problem. Additionally, if you're using CMake 3.0 or later you'll need apply the following patch to enable hypre.
```
--- a/config/SundialsHypre.cmake
+++ b/config/SundialsHypre.cmake
@@ -36,7 +36,7 @@ if(HYPRE_LIBRARIES)
   file(MAKE_DIRECTORY ${HYPRETest_DIR})
   # Create a CMakeLists.txt file 
   file(WRITE ${HYPRETest_DIR}/CMakeLists.txt
-    "CMAKE_MINIMUM_REQUIRED(VERSION 2.2)\n"
+    "CMAKE_MINIMUM_REQUIRED(VERSION 2.4)\n"
     "PROJECT(ltest C)\n"
     "SET(CMAKE_VERBOSE_MAKEFILE ON)\n"
     "SET(CMAKE_BUILD_TYPE \"${CMAKE_BUILD_TYPE}\")\n"
```

**Comment by fertinaz** [comment]
@gardner48 Thanks very much, looks like I missed it.

Regarding the Hypre patch, is it the following error:
```
Linking C shared library libsundials_nvecparhyp.so
/usr/bin/ld: /home/ertinaz/hypre/hypre-2.11.2-install/lib/libHYPRE.a(HYPRE_parcsr_vector.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/ertinaz/hypre/hypre-2.11.2-install/lib/libHYPRE.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvec_parhyp/libsundials_nvecparhyp.so.3.1.2] Error 1
make[1]: *** [src/nvec_parhyp/CMakeFiles/sundials_nvecparhyp_shared.dir/all] Error 2
make: *** [all] Error 2
```
I am using cmake version 2.8.12.2 though.

**Comment by balos1** [comment]
@fertinaz That is not the error the patch fixes. That patch is only needed if you are on CMake >= 3.0 because CMake >= 3.0 does not support CMake < 2.4.  

Your error is something different. When did that error occur for you? When you were building SUNDIALS?

**Comment by fertinaz** [comment]
@balos1 I've downloaded source code yesterday:
https://computation.llnl.gov/projects/sundials/download/sundials-3.1.2.tar.gz
and prepared the shell script above. CentOS version is 7.3

I've installed hypre-2.11.2 using the standard "configure && make install"

**Comment by balos1** [comment]
I believe the error is because you have compiled HYPRE improperly for use as a shared library. When running configure for HYPRE try adding `--enable-shared` which will produce libHYPRE.so. Or you could disable shared libraries in SUNDIALS by setting `BUILD_SHARED_LIBS` to `OFF`.

**Comment by fertinaz** [comment]
@balos1 Thanks disabling shared libs is the solution.
