### ISSUE TITLE
6.7.0 failed to build with open-mpi 5.0

### ISSUE THREAD

**Issue by chenrui333** [LLNL/sundials#405]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  -- Could NOT find MPI_Fortran (missing: MPI_Fortran_WORKS) (Required is at least version "2.0.0")
  CMake Error at /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find MPI (missing: MPI_Fortran_FOUND) (found suitable version
    "3.1", minimum required is "2.0.0")
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/7255959929/job/19767581428
relates to Homebrew/homebrew-core#157709

**Comment by balos1** [comment]
This error usually comes up if the build is using an MPI that was built with a compiler that doesn't agree with the one used as the CMAKE_C_COMPILER.

**Comment by chenrui333** [comment]
@balos1 thanks for the pointer, looks like re-compiling open-mpi works for my sundials build.

**Comment by chenrui333** [comment]
but looking at the build context for open-mpi and sundials, the gcc version got used are the same (ie 13.2.0):

- https://github.com/Homebrew/homebrew-core/tree/702ba581a914d6bec9be3ca11e21300aaf9a34db
- https://github.com/Homebrew/homebrew-core/tree/87ae9c648783f1ec32be232aff42894e6b7c8d51

**Comment by chenrui333** [comment]
[open-mpi rebuild](https://github.com/Homebrew/homebrew-core/pull/157775) works for my sundials build, thanks!
