### ISSUE TITLE
Duplicated symbols in libsundials_ida.a and libsundials_sunlinsolklu.a 

### ISSUE THREAD

**Issue by geofjamg** [LLNL/sundials#408]
Hello,

I'm trying to statically link libsundials_ida.a and libsundials_sunlinsolklu.a  to my program but the linker complains about duplicated symbols in this 2 libs, which seems to be true:
```
nm libsundials_sunlinsolklu.a | grep _N_VConst
0000000000000c98 T _N_VConst
00000000000015b8 T _N_VConstVectorArray
0000000000001070 T _N_VConstrMask
0000000000001f44 T _N_VConstrMaskLocal
...
nm libsundials_ida.a | grep _N_VConst
0000000000000c98 T _N_VConst
00000000000015b8 T _N_VConstVectorArray
0000000000001070 T _N_VConstrMask
0000000000001f44 T _N_VConstrMaskLocal
...
```
The only workaround I found is to add "-Wl,--allow-multiple-definition" to the g++ linker which is not a clean solution and also does not work with clang as is seems there is not an equivalent option for that.

There is no more issue when patching sundials sources like this:
```
--- sundials/src/sunlinsol/klu/CMakeLists.txt
+++ sundials.patched/src/sunlinsol/klu/CMakeLists.txt
@@ -25,7 +25,6 @@
   INCLUDE_SUBDIR
     sunlinsol
   OBJECT_LIBRARIES
-    sundials_generic_obj
   LINK_LIBRARIES
     PUBLIC sundials_sunmatrixsparse SUNDIALS::KLU
   OUTPUT_NAME
``` 

Do I miss something or is there really an issue?

**Comment by balos1** [comment]
Hi @geofjamg. Thanks for reporting this issue. It looks like the patch may be needed, but I will investigate this further.

**Comment by balos1** [comment]
Fixed in SUNDIALS v7
