### ISSUE TITLE
Type conversion (maybe corrupting data)?

### ISSUE THREAD

**Issue by sn248** [LLNL/sundials#409]
Hi 

I am trying to update my R package sundialr which is an interface to some of the solvers in SUNDIALS. The CRAN checks for my package give -Woverflow warnings. I discussed this issue in r-package-devel forum where another user thought I should bring it to the attention of the library since it may be corrupting data.

See the entire issue here - 

https://stat.ethz.ch/pipermail/r-package-devel/2024q1/010431.html

I am not able to submit to CRAN due to this error.

Specifically, these are the warnings I am getting

>Flavor: r-devel-windows-x86_64
>Check: whether package can be installed, Result: WARNING
>  Found the following significant warnings:
>    ./sundials/sundials/sundials_hashmap.h:26:48: warning: conversion from
>'long long unsigned int' to 'long unsigned int' changes value from
>'14695981039346656037' to '2216829733' [-Woverflow]
>    ./sundials/sundials/sundials_hashmap.h:27:48: warning: conversion from
>'long long unsigned int' to 'long unsigned int' changes value from
>'1099511628211' to '435' [-Woverflow]
>    sundials/sundials/sundials_hashmap.h:26:48: warning: conversion from
>'long long unsigned int' to 'long unsigned int' changes value from
>'14695981039346656037' to '2216829733' [-Woverflow]
>    sundials/sundials/sundials_hashmap.h:27:48: warning: conversion from
>'long long unsigned int' to 'long unsigned int' changes value from
>'1099511628211' to '435' [-Woverflow]
>    sundials/sundials/sundials_profiler.c:71:24: warning: function
>declaration isn't a prototype [-Wstrict-prototypes]
>  See 'd:/RCompile/CRANincoming/R-devel/sundialr.Rcheck/00install.out' for
>details.
>  Used C++ compiler: 'g++.exe (GCC) 12.3.0'

and 

>Flavor: r-devel-linux-x86_64-debian-gcc
>Check: whether package can be installed, Result: WARNING
>  Found the following significant warnings:
>    sundials/sundials/sundials_profiler.c:71:41: warning: a function
>declaration without a prototype is deprecated in all versions of C
>[-Wstrict-prototypes]
>  See '/srv/hornik/tmp/CRAN/sundialr.Rcheck/00install.out' for details.
>  Used C++ compiler: 'Debian clang version 17.0.6 (5)'

Any update on this would be highly appreciated!

**Comment by s-u** [comment]
To be more specific here (and not rely on external links) - in several places the sundials C code assumes that the `long` type is a 64-bit integer type, however, that assumption is wrong. The C standard defines the `long` type as at least 32-bit and on Windows it is exactly 32-bit. Above are some instances listed where 64-bit constants are cast to `unsigned long` and thus truncated to 32-bit, but generally, there are more places in the code where the `long` type is used incorrectly.

To fix, any uses of `unsigned long` where 64-bit integer is expected should be changed to `uint64_t` (and any signed use to `int64_t`) which is guaranteed to be 64-bit integer type.

**Comment by balos1** [comment]
@s-u  Yes, this is something we would like to fix now that we will not be tied to supporting C89 with SUNDIALS 7.0.0

**Comment by balos1** [comment]
Related https://github.com/LLNL/sundials/issues/249.

**Comment by s-u** [comment]
@balos1 great!

Not sure I get your C89 comment, though, since you can't get away without using C99 since `long long` is only defined since C99 - but so are all the `int64_t` types so there is really no way to write any portable 64-bit code without it. Not that it matters IMHO as it is 25 years later and everyone supports it ...

**Comment by s-u** [comment]
Thanks, much appreciated!
