### ISSUE TITLE
Minor documentation error in N_VAbs

### ISSUE THREAD

**Issue by jcc242** [LLNL/sundials#42]
Hi,

There appears to be a very minor documentation error of the N_VAbs function of the N_Vector API. See page 91 of this document: https://computing.llnl.gov/sites/default/files/public/kin_guide.pdf

The description is: 
> Sets the components of the N_Vector z to be the absolute values of the components of the N_Vector x: y_i=|x_i|, i= 0,...,n−1.

I believe it should be:
> Sets the components of the N_Vector z to be the absolute values of the components of the N_Vector x: z_i=|x_i|, i= 0,...,n−1.

Note the change of y_i to z_i as there is no vector y defined in this scope.

**Comment by balos1** [comment]
Fixed in v5.4.0.
