### ISSUE TITLE
gcc 10.1 and duplicated definitions

### ISSUE THREAD

**Issue by andrecbarros** [LLNL/sundials#43]
The issue arises from gcc 10.1 changing its default behavior compilation options to use -fno-common. Giving -fcommon fixes the issue.

When using gcc 10.1, the building process would stop with the following report:

[ 63%] Linking Fortran executable ark_bruss
cd /usr/src/packages/BUILD/sundials-5.3.0/build/examples/arkode/F90_serial && /usr/bin/cmake -E cmake_link_script CMakeFiles/ark_bruss.dir/link.txt --verbose=1
/usr/bin/gfortran  -L/usr/lib64 -lopenblas_openmp -lgomp -lm   -lsuperlumt_d -lsuperlu -lHYPRE_mt  -lklu -fPIC -pthread -fopenmp -D__OPENMP -D__PTHREAD  -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wl,-z,relro -Wl,-z,now -Wl,--as-needed CMakeFiles/ark_bruss.dir/ark_bruss.f90.o  -o ark_bruss  ../../../src/arkode/fcmix/libsundials_farkode.a ../../../src/arkode/libsundials_arkode.so.4.3.0 ../../../src/nvector/serial/libsundials_fnvecserial.so.5.3.0 ../../../src/nvector/serial/libsundials_nvecserial.so.5.3.0 -lm /usr/lib64/librt.so -lm 
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_dense.c.o):(.bss+0x18): multiple definition of `F2C_IDA_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x18): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_dense.c.o):(.bss+0x8): multiple definition of `F2C_ARKODE_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_dense.c.o):(.bss+0x20): multiple definition of `F2C_CVODE_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x20): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_dense.c.o):(.bss+0x10): multiple definition of `F2C_KINSOL_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x10): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_dense.c.o):(.bss+0x0): multiple definition of `F2C_ARKODE_mass_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x0): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_dense.c.o):(.bss+0x18): multiple definition of `F2C_IDA_linsol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x18): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_dense.c.o):(.bss+0x8): multiple definition of `F2C_ARKODE_linsol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_dense.c.o):(.bss+0x10): multiple definition of `F2C_KINSOL_linsol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x10): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_dense.c.o):(.bss+0x20): multiple definition of `F2C_CVODE_linsol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x20): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_dense.c.o):(.bss+0x0): multiple definition of `F2C_ARKODE_mass_sol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x0): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(farknulllinsol.c.o):(.bss+0x8): multiple definition of `F2C_ARKODE_linsol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(farknulllinsol.c.o):(.bss+0x0): multiple definition of `F2C_ARKODE_mass_sol'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunlinsol_band.c.o):(.bss+0x0): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(farknullmatrix.c.o):(.bss+0x8): multiple definition of `F2C_ARKODE_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x8): first defined here
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: ../../../src/arkode/fcmix/libsundials_farkode.a(farknullmatrix.c.o):(.bss+0x0): multiple definition of `F2C_ARKODE_mass_matrix'; ../../../src/arkode/fcmix/libsundials_farkode.a(fsunmatrix_band.c.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [examples/arkode/F90_serial/CMakeFiles/ark_bruss.dir/build.make:112: examples/arkode/F90_serial/ark_bruss] Error 1
make[2]: Leaving directory '/usr/src/packages/BUILD/sundials-5.3.0/build'
make[1]: *** [CMakeFiles/Makefile2:5060: examples/arkode/F90_serial/CMakeFiles/ark_bruss.dir/all] Error 2
make[1]: Leaving directory '/usr/src/packages/BUILD/sundials-5.3.0/build'
make: *** [Makefile:164: all] Error 2
make: Leaving directory '/usr/src/packages/BUILD/sundials-5.3.0/build'
error: Bad exit status from /var/tmp/rpm-tmp.UqFLKO (%install)

It should be noted that, at least, fsunmatrix_dense.c, fsunmatrix_sparse.c and fsunmatrix_band.c share clashing definitions of global variables and, perhaps, should be changed by moving the definitions to a separated file.

Best regards.

**Comment by balos1** [comment]
The F77 interfaces are deprecated so closing this.
