### ISSUE TITLE
7.0.0 release build failure

### ISSUE THREAD

**Issue by chenrui333** [LLNL/sundials#436]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  [ 50%] Building C object CMakeFiles/ltest.dir/ltest.c.o
  /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -I/usr/local/opt/suite-sparse/include -O3 -DNDEBUG -std=gnu99 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -MD -MT CMakeFiles/ltest.dir/ltest.c.o -MF CMakeFiles/ltest.dir/ltest.c.o.d -o CMakeFiles/ltest.dir/ltest.c.o -c /tmp/sundials-20240306-5618-nkv28f/sundials-7.0.0/build/KLU_TEST/ltest.c
  /tmp/sundials-20240306-5618-nkv28f/sundials-7.0.0/build/KLU_TEST/ltest.c:1:10: fatal error: 'klu.h' file not found
  #include "klu.h"
           ^~~~~~~
  1 error generated.
  make[2]: *** [CMakeFiles/ltest.dir/ltest.c.o] Error 1
  make[1]: *** [CMakeFiles/ltest.dir/all] Error 2
  make: *** [all] Error 2
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8165362852/job/22324343392?pr=165191
relates to Homebrew/homebrew-core#165191

**Comment by gardner48** [comment]
When building SUNDIALS, Homebrew is setting `KLU_INCLUDE_DIR` to `/opt/homebrew/opt/suite-sparse/include` which was correct for older versions of SuiteSparse. Recent versions (I believe starting with 7.4.0) have moved the headers to `/opt/homebrew/opt/suite-sparse/include/suitesparse` and the Homebrew formula needs to be updated accordingly.
