### ISSUE TITLE
Infinite loop in CVodeF

### ISSUE THREAD

**Issue by aseyboldt** [LLNL/sundials#44]
Under certain conditions the forward solver of cvodes enters an infinite loop if called using `CV_NORMAL_STEP`. If the step-size decreases until `t + h = t` numerically, then [CVode](https://github.com/LLNL/sundials/blob/master/src/cvodes/cvodea.c#L504) will print a warning, but still return a 0 return value. The loop [here](https://github.com/LLNL/sundials/blob/master/src/cvodes/cvodea.c#L500) in `CVodeF` will continue forever.

I do not have a reproducing example in C, but here is one that uses the [sunode](https://github.com/aseyboldt/sunode) package to wrap sundials:

We start integrating the ode `dy/dt = 1 / (t - 1)` at `t0 = 1 + 1e-15`:

```python
import sunode
import sunode.symode
import numpy as np

params = {'p': ()}
states = {'a': ()}

def rhs(t, y, p):
    return {
        'a': 1 / (t - 1)
    }

problem = sunode.SympyProblem(
    params=params,
    states=states,
    derivative_params=[('p',)],
    rhs_sympy=rhs,
)

solver = sunode.solver.AdjointSolver(problem)
solver.set_params_dict({'p': 0.})

h = 1e-15
tvals = np.linspace(1 + h, 1 + 1000 * h)
out, *_ = solver.make_output_buffers(tvals)

y0 = np.array(0.)
solver.solve_forward(1 + h, tvals, y0, out)
```

The solver prints error messages repeatedly until the maximum number of warnings in exhausted, then silently continues:
```
[CVODES WARNING]  CVode
  Internal t = 1 and h = 4.96507e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODES WARNING]  CVode
  Internal t = 1 and h = 4.96507e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODES WARNING]  CVode
  Internal t = 1 and h = 4.96507e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODES WARNING]  CVode
  Internal t = 1 and h = 4.96507e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODES WARNING]  CVode
  The above warning has been issued mxhnil times and will not be issued again for this problem.
```

CC @astoeriko

**Comment by balos1** [comment]
What version of sundials does sunode interface to?

**Comment by aseyboldt** [comment]
This is using the latest version on conda-forge, so 5.3.0.

**Comment by aseyboldt** [comment]
@balos1 Is there anything I can do to help fix this issue and #31?
Both make it quite hard for me to actually use sundials. Weird parameter combinations happen a lot when sampling posteriors.

**Comment by balos1** [comment]
A reproducing example in C would be very helpful. I am going to try and take a look at this soon.

**Comment by aseyboldt** [comment]
Thats great, thanks!
I'll port the example from the description tomorrow.

**Comment by aseyboldt** [comment]
I modified on of the examples so that it shows this infinite loop problem:
https://gist.github.com/aseyboldt/714633c5c3b6e8f91e1ec629d85aba0e

**Comment by balos1** [comment]
@aseyboldt I was able to reproduce the problem with that example, and we are working on fixing the problem.

**Comment by aseyboldt** [comment]
That's great.
Just to make sure we don't do the same thing more than one time unnecessarily: I think the patch in #45 solves the issue.

**Comment by aseyboldt** [comment]
Any news on this?

**Comment by balos1** [comment]
@aseyboldt This will be fixed in the next release.

**Comment by aseyboldt** [comment]
Thanks!
