### ISSUE TITLE
Error Handler Memory Leak

### ISSUE THREAD

**Issue by Steven-Roberts** [LLNL/sundials#466]
If more than default error handler is added to a `SUNContext`, it does not get free'd in `SUNContext_Free`.

https://github.com/LLNL/sundials/blob/2abd63bd6cbc354fb4861bba8e98d0b95d65e24a/src/sundials/sundials_context.c#L288

https://github.com/LLNL/sundials/blob/2abd63bd6cbc354fb4861bba8e98d0b95d65e24a/src/sundials/sundials_errors.c#L42-L47

Either `SUNContext_Free` or `SUNErrHandler_Destroy` should traverse the list of error handlers through `sunctx->err_handler->previous` to free each.

**Comment by gardner48** [comment]
> https://github.com/LLNL/sundials/blob/2abd63bd6cbc354fb4861bba8e98d0b95d65e24a/src/sundials/sundials_context.c#L288

This call to `SUNErrHandler_Destory` should be replaced with `SUNContext_ClearErrHandlers`

**Comment by Steven-Roberts** [comment]
Ah great, there's already a function to do that. I swapped in `SUNContext_ClearErrHandlers` and valgrind reports no leaks. I'll turn it into a PR.

**Comment by balos1** [comment]
Closed by #467
