### ISSUE TITLE
Fortran interface on 32 bits machines?

### ISSUE THREAD

**Issue by dirteat** [LLNL/sundials#468]
It is been around since a few versions, and may be that is not supposed to work.
For Sundials 7.0.0, building on 32 bits arches (i686, arm) produces tons of errors like this:

```
128 |     x => FN_VMake_Serial(N, xdata, sunctx)
      |         1
Error: Type mismatch in argument 'vec_length' at (1); passed INTEGER(4) to INTEGER(8)
/home/iurt/rpmbuild/BUILD/sundials-7.0.0/examples/nvector/serial/test_fnvector_serial_mod.f90:43:9:
```
It looks like that would be fixable with some PP conditionals. I have also tried SUNDIAL_INDEX_SIZES=32, but the build stops with a message claiming that F interface is not supported for 32 bits.

Thank you,
Best,
Chris.

**Comment by gardner48** [comment]
@dirteat currently the Fortran interfaces require using 64-bit integers however, #447 is adding Fortran interfaces with support for 32-bit integers. Try building from the `feature/fortran-32index-build` branch and please let us know if you run into any issues.

**Comment by balos1** [comment]
Resolved by #447.

**Comment by dirteat** [comment]
Thank you for all that work! I gave a try to sundials 7.1.1, but I do not pass the configuration step. Looks like the size of suiteparse long integer is not matching what sunindextype would like it to be (built on real i686).

```
-- Found KLU: /usr/lib/libklu.so
-- KLU_LIBRARIES:   /usr/lib/libklu.so;/usr/lib/libamd.so;/usr/lib/libcolamd.so;/usr/lib/libbtf.so;/usr/lib/libsuitesparseconfig.so
-- KLU_INCLUDE_DIR: /usr/include/suitesparse
-- Check size of SuiteSparse_long
-- Check size of SuiteSparse_long - done
-- Size of SuiteSparse_long is 4
CMake Error at cmake/tpl/SundialsKLU.cmake:72 (message):
  Size of 'sunindextype' is 8 but size of 'SuiteSparse_long' is 4.  KLU
  cannot be used.
Call Stack (most recent call first):
  cmake/SundialsSetupTPLs.cmake:113 (include)
  CMakeLists.txt:186 (include)
```

**Comment by dirteat** [comment]
But with -DENABLE_KLU=OFF, I do confirm the fortran interfaces are building fine.
