### ISSUE TITLE
KINSetMaxNewtonStep seems to have no effect (Sundials 4)

### ISSUE THREAD

**Issue by MartinOtter** [LLNL/sundials#5]
The function call KINSetMaxNewtonStep() to set the maximum stepsize for KINSOL seems to have no effect in Sundials 3.1.1. In Sundials 2.x, the function worked as expected (calling it just before KINSol). I tried to call it just before KINSol, and in the model function.

The issue is, that the default maximum stepsize = 0, if u0 is the zero vector. The value u0=0 is a standard value for simple DAEs as, e.g., defined with [Modia](https://github.com/ModiaSim/Modia.jl).

When calling KINGetStepLength(..) in the model function, indeed, a steplength=0 is returned all the time, until KINSol stops with an error that the Jacobian is singular. Since KINSetMaxNewtonStep(kinmem,1000.0) was called before KINSol and in the model function, the steplength should not be zero.

**Comment by balos1** [comment]
Nothing that should impact this routine has changed from SUNDIALS 2.x to 3.x. The referenced issue by @MartinOtter found that the problem was actually in the [Modia](https://github.com/ModiaSim/Modia.jl/issues/27) package that is using KINSOL.
