### ISSUE TITLE
minor leak in test

### ISSUE THREAD

**Issue by bjodah** [LLNL/sundials#50]
Caught with asan, looks like buf* is never free'd (two occurrences)?

sundials-5.4.0/examples/nvector/test_nvector.c:
```
   5293:  buf = (realtype*) malloc((size_t)size);
   5356:  buf = (realtype*) malloc((size_t)size);
```
(adding `free(buf)` before return allows test to pass at least).

**Comment by balos1** [comment]
Fixed by v5.6.0.
