### ISSUE TITLE
Error/warning reporting within MPI ranks

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/sundials#51]
Hello, we use SUNDIALS in our application PeleC (https://github.com/AMReX-Combustion/PeleC). When we run at large scales, we have instances of SUNDIALS running within each rank of sometimes 1000s of ranks. When SUNDIALS reports errors/warnings, we can get GB-sized text output. What recourse or best practices are there for us to avoid this? Ideally we would want to design our code so that we only output on the MPI rank dedicated to console I/O. However, in the short term, we could get by redirecting `stderr` to `/dev/null` or something, for example, but we don't want to lose `stderr` in the long term.

**Comment by gardner48** [comment]
@jrood-nrel By default SUNDIALS writes all warnings and error messages to `stderr`. If you're finding that this is not the case let me know what errors you're seeing and I'll check it out. 

If you want to direct the output somewhere else, you can set an output file with the function `*SetErrFile` where `*` is the integrator specific prefix. For example, with CVODE the function is `CVodeSetErrFile(cvode_mem, errfp)`.  If `errfp` is `NULL`, then error/warning message output is disabled (we generally discourage disabling the output though).

Alternatively, a user-defined error handling function (of type `*ErrHandlerFn` where `*` is `CV` for CVODE, `ARK` for ARKODE, etc.) can be attached with the `*SetErrHandlerFn` function for greater control over error/warning message output. For more details on this option see the documentation for `*ErrHandlerFn` in the user guides. 

Hope that helps and let me know if have any additional questions.

**Comment by gardner48** [comment]
I think the user-defined error handler is ultimately what you're looking for as this could be used to coordinate messages between different instances of the integrator for output from a single rank.

**Comment by jrood-nrel** [comment]
Thanks. I think I'm actually fine with only reporting the messages encountered on the I/O rank as a first step. Right now I'm looking into using `ARKStepErrFile` and setting it to `NULL` on everything but the I/O rank.

**Comment by gardner48** [comment]
That should work to get things started. You will lose the error messages from the other integrator instances since they don't coordinate with each other but as long as you're capturing the return values from `ARKStepEvolve` and handling any error/warnings as needed everything should be good.

**Comment by jrood-nrel** [comment]
I don't want to leave this open perpetually. I think we have the information to work on this within our application so I will close it.
