### ISSUE TITLE
How to use sundials in window VS studio based on Fortran langrague？

### ISSUE THREAD

**Issue by XinmengZeng** [LLNL/sundials#537]
Dear developer,
       
       i am new in this filed, can i ask for your help about how to use sundials in window VS studio based on Fortran langrague？

       Thanks a lot!

BEST
Simon

**Comment by balos1** [comment]
Please follow the steps outlined here for Windows systems: https://sundials.readthedocs.io/en/latest/sundials/Install_link.html#configuring-building-and-installing-on-windows.
