### ISSUE TITLE
klu support with suitesparse 5.8.1 (latest)

### ISSUE THREAD

**Issue by doronbehar** [LLNL/sundials#54]
Hi,

I'm the maintainer in NixOS of a few packages that use sundials and suitesparse as dependencies. While attempting to update our sundials from 5.3.0 to 5.6.1 I got this error when I try to build sundials 5.6.1 with suitesparse 5.8.1:

https://gist.github.com/doronbehar/e24f9fb894171c209bc436c3962ed5ee

I noticed you write in your docs that suitesparse 5.7.1 is the version that is tested for klu support, but it'd be nice if the latest version of suitesparse - available in the distributions will be supported and hence sundials will not require a custom version of suitesparse.

Regards.

**Comment by gardner48** [comment]
@doronbehar try changing `-DSUNDIALS_INDEX_SIZE=int32_t` to -DSUNDIALS_INDEX_SIZE=32` in your configuration and that should resolve the build issue.

**Comment by doronbehar** [comment]
That worked. Thanks!
