### ISSUE TITLE
Broken Link in ReadME 

### ISSUE THREAD

**Issue by dautovri** [LLNL/sundials#578]
<img width="895" alt="image" src="https://github.com/user-attachments/assets/82c9a480-37b7-4e4a-9d9d-64c5da618c25">

[online install guide](https://sundials.readthedocs.io/en/latest/Install_link.html) goes to https://sundials.readthedocs.io/en/latest/Install_link.html

<img width="948" alt="Screenshot 2024-09-24 at 12 11 50 PM" src="https://github.com/user-attachments/assets/4e421d86-1adf-4b88-8a39-1a187e7a8494">

**Comment by drreynolds** [comment]
This has already been fixed in the SUNDIALS branch, and will be included in the next release.
