### ISSUE TITLE
ARKode XBraid documentation uses `ARKBraid_Braid()`

### ISSUE THREAD

**Issue by yizhang-yiz** [LLNL/sundials#68]
`ark_guide-4.7.0` p. 154:
> 16. Initialize the ARKBraid interface
Call the initialization function ARKBraid_Braid() to create the XBraid core memory structure and attach
the ARKBraid interface app and functions.

Should `ARKBraid_Braid()` be `ARKBraid_BraidInit()` instead?

**Comment by balos1** [comment]
Fixed in v5.8.0.
