### ISSUE TITLE
Runtime error: double free or corruption (!prev) Aborted (core dumped)

### ISSUE THREAD

**Issue by yushimin13** [LLNL/sundials#77]
I was debugging a simulation program of single-frequency CCP discharge, and the latest cvode was called in the program. When I increased the time step, an error was reported, and the error message was as follows: double free or corruption (!prev) Aborted (core dumped).

There is no problem with the operation of the program when the simulation time step is small. I wonder if this error is caused by Sundials. I hope that an expert can answer my doubts. Thank you very much. The program source code is attached.

[code.zip](https://github.com/LLNL/sundials/files/7152737/code.zip)

The operating environment is WSL+VSCODE+oneAPI, compiled by Cmake, and written in Fortran. Sundials is the latest version.

**Comment by balos1** [comment]
Are you using the sundials Fortran 2003 interfaces? Can you post the stacktrace?

**Comment by balos1** [comment]
@yushimin13 Is this the same issue as https://github.com/LLNL/sundials/issues/78?

**Comment by balos1** [comment]
Closing this issue since there has been no response in awhile. Please feel to re-open if this is still an issue in the newer versions of SUNDIALS.
