### ISSUE TITLE
Mailing list archive unavailable

### ISSUE THREAD

**Issue by teambarrywhite** [LLNL/sundials#88]
The link on https://computing.llnl.gov/projects/sundials/mailing-list to reach the mailing list archive seems to be broken. It directs to http://sundials.2283335.n4.nabble.com/ which is not existing

**Comment by balos1** [comment]
We are currently in the process of moving the mailing list archive and will provide an updated link soon.

**Comment by balos1** [comment]
Note, if you want to send mail to the mailing list you still can by emailing sundials-users@llnl.gov.

**Comment by teambarrywhite** [comment]
Thanks for the quick reply
