### ISSUE TITLE
Wrong arguments in ClassicalGS

### ISSUE THREAD

**Issue by vitenti** [LLNL/sundials#9]
It seems that the two calls to ClassicalGS in sundials_spgmr.c:319 and sundials_spfgmr.c:272 have incompatible parameters. The last two should be (..., realtype *, N_Vector *) but their are (.., N_Vector, realtype *).

**Comment by gardner48** [comment]
The source files `src/sundials/sundials_spgmr.c` and `src/sundials/sundials_spfgmr/c` are deprecated and will be removed in a future release. The new implementation files are for SPGMR and SPFGMR are `src/sunlinsol_spgmr/sunlinsol_spgmr.c` and `src/sunlinsol_spfgmr/sunlinsol_spfgmr.c` respectively.

**Comment by balos1** [comment]
The deprecated source files have been removed in the 5.0.0-dev.0 release.
