### ISSUE TITLE
Memory not freed in int SUNLinSolFree_SuperLUMT(SUNLinearSolver S) due to logic issue

### ISSUE THREAD

**Issue by d5ch4k** [LLNL/sundials#91]
the cleanup process for L U and B  has the following identical issue: matrix substructures are freed and the the pointer to the matrix main structure is set to NULL and subsequently cannot be freed anymore. this results in a memory leak:
as an example for B:

    if (SM_B(S)) {
      Destroy_SuperMatrix_Store(SM_B(S));
      SM_B(S) = NULL; // <-------- 'SM_B(S)->Store' and everything below was freed but not 'SM_B(S)'
    }

so subsequently the following fails:

    if (SM_B(S)) {
      free(SM_B(S));
      SM_B(S) = NULL;
    }

this can be avoided when you free() also in the first if-clause and skip the second if () or avoid in the first if-clause the NULL setting

best regards
Martin

**Comment by balos1** [comment]
Fixed in SUNDIALS v6.1.0. Thanks!
