### ISSUE TITLE
Wrong variable name in examples/idas/serial/CMakeLists.txt

### ISSUE THREAD

**Issue by d5ch4k** [LLNL/sundials#92]
I guess
examples/idas/serial/CMakeLists.txt line 323: 

`set(EXAMPLES_SLUMTU "")` 

should be instead:

`set(EXAMPLES_SLUMT "") `

If you prefer to receive pull requests on such issues, please let me know.

regards
Martin

**Comment by balos1** [comment]
Closing since #93 is open and will be in SUNDIALS' next release. Thanks!
