### ISSUE TITLE
missed library sundials_nvecparallel

### ISSUE THREAD

**Issue by dxwu88** [LLNL/sundials#98]
missed sundials_nvecparallel library in the build and header file nvector_parallel.h when I used cmake to built the libraries on Ubuntu.

**Comment by balos1** [comment]
Can you provide some more information about this? I am not sure I understand what the problem is.

**Comment by dxwu88** [comment]
Hi Cody,

Thank you very much to take a look at this issue. After I download sundials 6.0.0 to my Ubuntu computer, I follow the installation instruction INSTALL_GUIDE.pfd which is included in the download package. Then I follow the instructions on section 1.1.1.2 Building from the command line of SUNDIALS Installation Guide, v6.0.0, which are:

The following will build the default configuration:
$ cmake -DCMAKE_INSTALL_PREFIX=/home/myname/sundials/instdir \
> -DEXAMPLES_INSTALL_PATH=/home/myname/sundials/instdir/examples \
> ../srcdir
$ make
$ make install

After I ran the above three commands, everything is working except the parallel part. Then I checked my install directories, there are no sundials_nvecparallel.so (or .a) and nvector_parallel.h.

Best regards,
David Wu


________________________________

**Comment by balos1** [comment]
Hi David,

You need to enable MPI for the parallel nvector. You can add `-DENABLE_MPI=TRUE` to your cmake command, and if you have MPI on your system it should pick it up. If not, you can tell CMake the path to the MPI compiler(s) with `-DMPI_C_COMPILER=/path/to/mpicc`.

**Comment by dxwu88** [comment]
Thanks Cody very much! Follow the instructions, the issue solved. The example MPI code works fine.
