### ISSUE TITLE
`src/sundials/sundials_context_impl.h` did not get installed per build

### ISSUE THREAD

**Issue by chenrui333** [LLNL/sundials#99]
👋  trying to upgrade sundials formula to use the latest release build, but found `src/sundials/sundials_context_impl.h` file did not get installed properly, thus, the regression tests broke. Let me know if that is intentional.

- relates to https://github.com/Homebrew/homebrew-core/pull/91607

**Comment by balos1** [comment]
`src/sundials/sundials_context_impl.h` should not be installed with `make install`.
